# 2026
- name: Mining Software Repositories (MSR) Industry Track 2026
  role: PC Member
  year: 2026
  website: https://2026.msrconf.org/track/msr-2026-industry-track

- name: IEEE International Conference on Software Analysis, Evolution and Reengineering (SANER) Tool Demo Track
  role: PC Member
  year: 2026
  website: https://conf.researchr.org/track/saner-2026/saner-2026-tool-demo-track

# 2025
- name:  Empirical Software Engineering (EMSE)
  role: Invited Reviewer
  year: 2025
  website: https://link.springer.com/journal/10664

- name:  ACM Transactions on Software Engineering and Methodology (TOSEM)
  role: Invited Reviewer
  year: 2025
  website: https://dl.acm.org/journal/tosem

- name: Information and Software Technology
  role: Invited Reviewer
  year: 2025
  website: https://www.sciencedirect.com/journal/information-and-software-technology

- name: Journal of Systems & Software
  role: Invited Reviewer
  year: 2025
  website: https://www.sciencedirect.com/journal/journal-of-systems-and-software

- name: Reliable and Secure AI for Software Engineering (ReSAISE), Co-located with ISSRE
  role: PC Member
  year: 2025
  website: https://resaise.github.io/2025/html/committee.html

- name:  Science of Computer Programming | Journal
  role: Invited Reviewer
  year: 2025
  website: https://www.sciencedirect.com/journal/science-of-computer-programming

- name: Open Science for Foundation Models (SCI-FM), ICLR 2025
  role: PC Member
  year: 2025
  website: https://open-foundation-model.github.io/

- name: Deep Learning for Code (DL4C), ICLR 2025
  role: PC Member
  year: 2025
  website: https://dl4c.github.io/

- name: 16th International Conference on Internetware 2025
  role: PC Member
  year: 2025
  website: https://conf.researchr.org/track/internetware-2025/internetware-2025-research-track

- name: International Conference on Software Engineering (ICSE) Artifact Evaluation Track
  role: PC Member
  year: 2025
  website: https://conf.researchr.org/track/icse-2025/icse-2025-artifact-evaluation

- name: DeepTest 2025, Co-located with ICSE
  role: PC Member
  year: 2025
  website: https://conf.researchr.org/home/icse-2025/deeptest-2025

- name: Mining Software Repositories (MSR) Industry Track 2025
  role: PC Member
  year: 2025
  website: https://2025.msrconf.org/track/msr-2025-industry-track/

- name: Mining Software Repositories (MSR) 2025
  role: Junior PC Member
  year: 2025
  website: https://2025.msrconf.org/

- name: International Conference on Technical Debt (TechDebt) 2025
  role: Junior PC Member
  year: 2025
  website: https://conf.researchr.org/home/TechDebt-2025

- name: International Conference on Software Engineering (ICSE)
  role: Co-Reviewer
  year: 2025
  website: https://conf.researchr.org/home/icse-2025

# 2024
- name: Reliable and Secure AI for Software Engineering (ReSAISE), Co-located with ISSRE
  role: PC Member
  year: 2024
  website: https://resaise.github.io/2024/index.html

- name:  ACM Transactions on Software Engineering and Methodology (TOSEM)
  role: Invited Reviewer
  year: 2024
  website: https://dl.acm.org/journal/tosem

- name: Journal of Systems & Software
  role: Special Issue (Invited Reviewer)
  year: 2024
  website: https://www.sciencedirect.com/journal/journal-of-systems-and-software

- name: International Conference on Automated Software Engineering (ASE)
  role: PC Member
  year: 2024
  website: https://conf.researchr.org/track/ase-2024/ase-2024-industry-showcase

- name: Journal of Software - Evolution and Process
  role: Invited Reviewer
  year: 2024
  website: https://onlinelibrary.wiley.com/journal/20477481

- name: Forge 2024, Co-located with ICSE
  role: PC Member
  year: 2024
  website: https://conf.researchr.org/home/forge-2024

# 2024
- name: DeepTest 2024, Co-located with ICSE
  role: PC Member
  year: 2024
  website: https://conf.researchr.org/home/icse-2024/deeptest-2024

# 2024
- name: LLM4Code 2024, Co-located with ICSE
  role: Co-Reviewer
  year: 2024
  website: https://llm4code.github.io/

# 2023
- name: Reliable and Secure AI for Software Engineering (ReSAISE), Co-located with ISSRE
  role: PC Member
  year: 2023
  website: https://resaise.github.io/2023/committee.html

# 2023
- name: International Symposium on Software Testing and Analysis (ISSTA)
  role: Co-Reviewer
  year: 2023
  website: https://conf.researchr.org/home/issta-2023

# 2021
- name: Foundations of Software Engineering (ESEC/FSE)
  role: Co-Reviewer
  year: 2021
  website: https://2021.esec-fse.org/

# 2021
- name: International Conference on Software Engineering (ICSE)
  role: Co-Reviewer
  year: 2021
  website: https://conf.researchr.org/home/icse-2021

# 2020
- name: International Conference on Software Engineering (ICSE)
  role: Co-Reviewer
  year: 2020
  website: https://conf.researchr.org/home/icse-2021

# 2020
- name: International Symposium on Software Testing and Analysis (ISSTA)
  role: Co-Reviewer
  year: 2020
  website: https://conf.researchr.org/home/issta-2020